// <auto-generated />
using System;
using MegaFintradeRiskMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MegaFintradeRiskMonitor.Data.Migrations
{
    [DbContext(typeof(RiskMonitorDbContext))]
    [Migration("20260507183825_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("MegaFintradeRiskMonitor.Models.MonitoringSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveAlertCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CriticalAlertCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HighAlertCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImportAuditAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImportRejectionsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JavaBackendBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("JavaBackendReachable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LowAlertCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediumAlertCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PortfolioMonitoringAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReportSummaryAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SymbolCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SymbolMonitoringAvailable")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("JavaBackendReachable");

                    b.HasIndex("Status");

                    b.ToTable("MonitoringSnapshots");
                });

            modelBuilder.Entity("MegaFintradeRiskMonitor.Models.RiskAlert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEndpoint")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValue")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThresholdValue")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsActive");

                    b.HasIndex("Symbol");

                    b.HasIndex("Type", "Symbol", "SourceEndpoint", "IsActive");

                    b.ToTable("RiskAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
